# Generated by Django 4.1.5 on 2023-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myfashionbeauty", "0002_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(default="none", max_length=50),
        ),
    ]
