# Generated by Django 4.1.5 on 2023-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myfashionbeauty", "0003_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
