# Generated by Django 4.1.5 on 2023-04-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myfashionbeauty", "0004_order_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
