# Generated by Django 4.1.5 on 2023-04-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myfashionbeauty", "0006_order_orderitem_order_shippingaddress_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
