# Generated by Django 4.1.5 on 2023-04-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myfashionbeauty", "0008_alter_order_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
